version: "3.8"

services:
  postgres:
    container_name: restaurant-db
    image: postgres:12.8
    restart: always
    env_file: ${ENV_FILE:-.env.development}
    environment:
      POSTGRES_USER: tech_challenge_usr
      POSTGRES_PASSWORD: tech_challenge_pwd
      POSTGRES_DB: restaurant_db
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    networks:
      - restaurant-network

  api:
    build:
      context: .
    container_name: restaurant-api
    restart: always
    environment:
      APP_NAME: "${APP_NAME:-restaurant-api}"
      APP_ENV: "${APP_ENV:-development}"
      HTTP_URL: "${HTTP_URL:-127.0.0.1}"
      HTTP_PORT: "${HTTP_PORT:-:8080}"
      DB_CONNECTION: "${DB_CONNECTION:-postgres}"
      DB_HOST: "${DB_HOST:-localhost}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_DATABASE: "${DB_DATABASE:-restaurant_db}"
      DB_USERNAME: "${DB_USERNAME:-usr}"
      DB_PASSWORD: "${DB_PASSWORD:-pwd}"
    ports:
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
