version: "3.8"

services:
  postgres:
    container_name: restaurant-db
    image: postgres:12.8
    restart: always
    env_file: ${ENV_FILE:-.env.development}
    environment:
      POSTGRES_USER: tech_challenge_usr
      POSTGRES_PASSWORD: tech_challenge_pwd
      POSTGRES_DB: restaurant_db
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    networks:
      - restaurant-network

  api:
    build:
      context: .
    container_name: restaurant-api
    restart: always
    environment:
      APP_NAME: "${APP_NAME:-restaurant-api}"
      APP_ENV: "${APP_ENV:-development}"
      HTTP_URL: "${HTTP_URL:-127.0.0.1}"
      HTTP_PORT: "${HTTP_PORT:-:8080}"
      DB_CONNECTION: "${DB_CONNECTION:-postgres}"
      DB_HOST: "${DB_HOST:-localhost}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_DATABASE: "${DB_DATABASE:-restaurant_db}"
      DB_USERNAME: "${DB_USERNAME:-usr}"
      DB_PASSWORD: "${DB_PASSWORD:-pwd}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - restaurant-network

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEFAULT_REGION=us-east-1
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  restaurant-network:
    driver: bridge
