apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-api
  template:
    metadata:
      labels:
        app: restaurant-api
    spec:
      containers:
        - name: restaurant-api
          image: fabianogoes/restaurant-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
          envFrom:
            - secretRef:
                name: restaurant-secret
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: POSTGRES_PASSWORD
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: TOKEN_SECRET
            - name: CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: CRYPTO_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: AWS_SESSION_TOKEN
            - name: AWS_ENDPOINT
              value: https://sqs.us-east-1.amazonaws.com
            - name: AWS_REGION
              value: us-east-1
            - name: DB_PORT
              value: "5432"
            - name: APP_NAME
              value: restaurant-api
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: ":8080"
            - name: API_VERSION
              value: "5.0"
            - name: PAYMENT_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/252506243013/order-payment-queue"
            - name: PAYMENT_CALLBACK_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/252506243013/order-payment-callback-queue"
            - name: KITCHEN_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/252506243013/order-kitchen-queue"
            - name: KITCHEN_CALLBACK_QUEUE_URL
              value: https://sqs.us-east-1.amazonaws.com/252506243013/order-kitchen-callback-queue
      restartPolicy: Always
