apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-api
  template:
    metadata:
      labels:
        app: restaurant-api
    spec:
      containers:
        - name: restaurant-api
          image: fabianogoes/restaurant-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
          envFrom:
            - secretRef:
                name: restaurant-secret
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: POSTGRES_PASSWORD
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: TOKEN_SECRET
            - name: DB_PORT
              value: "5432"
            - name: APP_NAME
              value: restaurant-api
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: ":8080"
            - name: API_VERSION
              value: "4.0.0"
            - name: PAYMENT_API_URL
              value: "http://a22d56d187d3b4166aa01bbffcc23a7e-212615449.us-east-1.elb.amazonaws.com:8080"
            - name: KITCHEN_API_URL
              value: "http://a74ca961315474c7b9d6fb3c31020ebf-2145173620.us-east-1.elb.amazonaws.com:8080"
      restartPolicy: Always
