apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secret
  labels:
    app: restaurant-secret
type: Opaque
data:
  DB_CONNECTION: cG9zdGdyZXM6Ly90ZWNoX2NoYWxsZW5nZV91c3I6dGVjaF9jaGFsbGVuZ2VfcHdkQHRlY2gtY2hhbGxlbmdlLWRiLmNzcGllZmR6MHF0My51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9yZXN0YXVyYW50X2Ri
  TOKEN_SECRET: S09LWGxlS0F2K0tYbFNrZ0lIVERvU0J2YkdoaGJtUnZJRzhnY1hWbElHRnhkV2tnYldGdXc2a2dQejgvSUNqaWw1WGlnTC9pbDVVcAo=
