apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: app-secret
type: Opaque
data:
  DB_CONNECTION: cG9zdGdyZXM=
  TOKEN_SECRET: S09LWGxlS0F2K0tYbFNrZ0lIVERvU0J2YkdoaGJtUnZJRzhnY1hWbElHRnhkV2tnYldGdXc2a2dQejgvSUNqaWw1WGlnTC9pbDVVcAo=